repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v5.0.0"
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-json
        exclude: ^(\.vscode/launch\.json|\.devcontainer/devcontainer\.json)$
      - id: pretty-format-json
        exclude: ^(\.vscode/launch\.json|\.devcontainer/devcontainer\.json)$
        args: [--autofix]
      - id: check-toml
      - id: check-yaml

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.6.3"
    hooks:
      - id: ruff
        args: [--exit-non-zero-on-fix, --config=pyproject.toml]
      - id: ruff-format
        args: [--config=pyproject.toml]

exclude: ^api/gRPC/generated/
