
services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/python:1-3.12-bullseye

    volumes:
      - ".:/workspace:cached"
    environment:
      - PORT=8080
      - POSTGRES_HOST=db
    env_file:
      - .env
    command: ["sleep", "infinity"]


  db:
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres-init.dev.sql:/docker-entrypoint-initdb.d/init.sql # create test db
    ports: ["5432:5432"]
    env_file:
      - .env


volumes:
  pgdata:
