services:
  db:
    image: postgres:15.2
    env_file:
      - .env
    environment:
      - POSTGRES_DB=test
    expose: ["5432:5432"]

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]

  tests:

    build:
      context: .
      dockerfile: tests.Dockerfile

    depends_on:
      db:
        condition: service_healthy

    env_file:
      - .env
    environment:
      - PORT=80
      - POSTGRES_HOST=db
      - POSTGRES_DB=test
