services:
  db:
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]

  api:
    build:
      context: .
      dockerfile: Dockerfile

    depends_on:
      db:
        condition: service_healthy

    env_file:
      - .env

    ports: ["80:80"]
    restart: always
    environment:
      - PORT=80
      - POSTGRES_HOST=db


volumes:
  pgdata:
