openapi: '3.0.3'
info:
  title: Schedule API
  version: '1.0'





paths:
  /users:
    get:
      tags: ['Users']
      parameters:
        - name: user_id
          in: query
          required: true
          schema:
            type: integer
            title: User Id

      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserReadResponse'





components:
  schemas:
    UserReadResponse:
      properties:
        id:
          type: integer
          title: User Id
        name:
          type: string
          title: User name
