# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-04-23T19:18:41+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class UserReadResponse(BaseModel):
    id: int | None = Field(None, title="User Id")
    name: str | None = Field(None, title="User name")
