# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-05-02T16:13:20+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class UserReadResponse(BaseModel):
    id: Optional[int] = Field(None, title='User Id')
    name: Optional[str] = Field(None, title='User name')
