"""treatment_duration may be constantly

Revision ID: 85cde8301fda
Revises: e9baf9389777
Create Date: 2025-03-15 17:52:57.572406

"""

from collections.abc import Sequence
from typing import Union

from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "85cde8301fda"
down_revision: Union[str, None] = "e9baf9389777"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("schedules", "treatment_duration", existing_type=postgresql.INTERVAL(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("schedules", "treatment_duration", existing_type=postgresql.INTERVAL(), nullable=False)
    # ### end Alembic commands ###
