"""change user_id to bigint

Revision ID: cfea4ef0043a
Revises: 34240cbe3168
Create Date: 2025-03-16 18:33:10.499744

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cfea4ef0043a"
down_revision: Union[str, None] = "34240cbe3168"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("schedules", "user_id", existing_type=sa.INTEGER(), type_=sa.BigInteger(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("schedules", "user_id", existing_type=sa.BigInteger(), type_=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
