"""deleted old field duration and added simple field intake_finish

Revision ID: a4fb97723d07
Revises: cfea4ef0043a
Create Date: 2025-03-18 14:04:03.317604

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a4fb97723d07"
down_revision: Union[str, None] = "cfea4ef0043a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("schedules", sa.Column("intake_finish", sa.DateTime(), nullable=True))
    op.add_column("schedules", sa.Column("intake_start", sa.DateTime(), nullable=False))
    op.drop_column("schedules", "treatment_duration")
    op.drop_column("schedules", "schedule_datetime")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "schedules",
        sa.Column(
            "schedule_datetime",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "schedules", sa.Column("treatment_duration", postgresql.INTERVAL(), autoincrement=False, nullable=True)
    )
    op.drop_column("schedules", "intake_start")
    op.drop_column("schedules", "intake_finish")
    # ### end Alembic commands ###
